version: "3"

services:
  hddcoin:
    image: ixsystems/hddcoin-docker:latest
    restart: always
    environment:
      - TZ="America/New_York"
      - keys="/my_key"
    volumes:
      - /mnt/hddcoin/data:/data
      - /mnt/hddcoin/plots:/plots
      - /mnt/hddcoin/my_keys:/my_keys
    ports:
      - 28444:28444
